"""initial schema with cascade + usage

Revision ID: a877b4c59e1a
Revises: 
Create Date: 2026-06-21 18:56:42.536323
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a877b4c59e1a'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tenants',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('jobs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('jd_text', sa.Text(), nullable=False),
    sa.Column('status', sa.Enum('draft', 'ready', 'archived', name='jobstatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('jobs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_jobs_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('usage_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('model', sa.String(length=128), nullable=False),
    sa.Column('tier', sa.Integer(), nullable=False),
    sa.Column('prompt_tokens', sa.Integer(), nullable=False),
    sa.Column('completion_tokens', sa.Integer(), nullable=False),
    sa.Column('cached_tokens', sa.Integer(), nullable=False),
    sa.Column('cost_usd', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('usage_records', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_usage_records_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_usage_records_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('candidates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('job_id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('filename', sa.String(length=512), nullable=False),
    sa.Column('parsed_text', sa.Text(), nullable=False),
    sa.Column('ats_score', sa.Float(), nullable=True),
    sa.Column('job_match_pct', sa.Float(), nullable=True),
    sa.Column('overall_score', sa.Float(), nullable=True),
    sa.Column('ats_issues', sa.JSON(), nullable=False),
    sa.Column('matched_keywords', sa.JSON(), nullable=False),
    sa.Column('missing_keywords', sa.JSON(), nullable=False),
    sa.Column('reasoning', sa.Text(), nullable=False),
    sa.Column('tier_reached', sa.Integer(), nullable=False),
    sa.Column('cache_hit', sa.Boolean(), nullable=False),
    sa.Column('est_cost_usd', sa.Float(), nullable=False),
    sa.Column('stage', sa.Enum('new', 'shortlisted', 'interview', 'rejected', name='candidatestage'), nullable=False),
    sa.Column('score_status', sa.Enum('pending', 'processing', 'scored', 'failed', 'filtered_out', name='scorestatus'), nullable=False),
    sa.Column('error', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('candidates', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_candidates_job_id'), ['job_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_candidates_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('scoring_criteria',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('job_id', sa.Integer(), nullable=False),
    sa.Column('required_skills', sa.JSON(), nullable=False),
    sa.Column('preferred_skills', sa.JSON(), nullable=False),
    sa.Column('min_years', sa.Integer(), nullable=False),
    sa.Column('must_haves', sa.JSON(), nullable=False),
    sa.Column('weights', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('scoring_criteria', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_scoring_criteria_job_id'), ['job_id'], unique=True)

    # ### end Alembic commands ###

    # NOTE: intentionally NO default-tenant seed. With per-user tenants (each
    # signup creates its own tenant), seeding an explicit id=1 row left the
    # Postgres SERIAL sequence pointing at 1, so the first real registration
    # collided on tenants_pkey. A fresh DB must start with an empty tenants
    # table so the sequence and the first INSERT agree.


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('scoring_criteria', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_scoring_criteria_job_id'))

    op.drop_table('scoring_criteria')
    with op.batch_alter_table('candidates', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_candidates_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_candidates_job_id'))

    op.drop_table('candidates')
    with op.batch_alter_table('usage_records', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_usage_records_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_usage_records_created_at'))

    op.drop_table('usage_records')
    with op.batch_alter_table('jobs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_jobs_tenant_id'))

    op.drop_table('jobs')
    op.drop_table('tenants')
    # ### end Alembic commands ###
